<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="77" started-at="2018-02-04T19:03:21Z" finished-at="2018-02-04T19:03:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="77" started-at="2018-02-04T19:03:21Z" finished-at="2018-02-04T19:03:21Z">
      <class name="com.synechron.mktx.testscripts.TC001_testLogin">
        <test-method status="FAIL" signature="testLogin()[pri:0, instance:com.synechron.mktx.testscripts.TC001_testLogin@d8355a8]" name="testLogin" duration-ms="45" started-at="2018-02-05T00:33:21Z" finished-at="2018-02-05T00:33:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.synechron.mktx.pagelibrary.Signin.clickonSignIn(Signin.java:32)
	at com.synechron.mktx.testscripts.TC001_testLogin.testLogin(TC001_testLogin.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="quitebrowser()[pri:0, instance:com.synechron.mktx.testscripts.TC001_testLogin@d8355a8]" name="quitebrowser" is-config="true" duration-ms="1" started-at="2018-02-05T00:33:21Z" finished-at="2018-02-05T00:33:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitebrowser -->
      </class> <!-- com.synechron.mktx.testscripts.TC001_testLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
